apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-py
  name: test-py
  namespace: test
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: test-py
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: test-py
  name: test-py
  namespace: test
spec:
  port:
    targetPort: 8090
  to:
    kind: Service
    name: test-py
    weight: 100
  wildcardPolicy: None
