apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-s3
  namespace: ns1-uwl
stringData:
  endpoint: https://s3.us-east-1.amazonaws.com
  bucket: tempo
  access_key_id: <access_key_id>
  access_key_secret: <access_key_secret>
type: Opaque
